### PR TITLE
Added functionality for opening and saving a collection TextGrid file…

### PR DESCRIPTION
**Pull request by polvanrijn**
…, aswell the option to save a Textgrid in the more readable long format

You can review the changes, if you want :+1: 

I really love your toolbox by the way :-)

### CODE REVIEW

**Comment by bbTomas** [comment]
Dear Pol,
I am glad you like the mPraat toolbox and thank you for your contribution. Although, I am afraid this extension is too specific that it may be rather confusing for general public audience.
The problem with collections is that they may contain a wide variety of objects (e.g., a number of textgrids - or - combination of textgrids and pitchtiers - or - combination of textgrids and sounds etc.)
If we limit the read function only to collections with exactly two specific objects (one textgrid and one sound - and the sound component is ignored), it may not cover the most typical expectations of the "collections handling" functionality. In fact, I do not recommend to make a text format collection with this combination of sound and textgrid because the sound component is stored very ineffectively (large size and very slow reading in comparison to the standard binary .wave file).
What I would prefer is to make possible read a collection with any number of textgrid and pitchtier components (and maybe also sounds, although I do not recommend to store sounds this way) to make the reading function more universal. This would be more complicated, which is the reason I have not implemented it so far.
It is good that you have managed to implement this new functionality to the toolbox but I think it is not in the point where it should be made public in the main base branch.
Thank you,
Tomas

**Comment by polvanrijn** [comment]
Dear Thomas,

That's true. I think it should not be too complicated, since you've already created modules for reading TextGrids and Pitchtiers. Can you maybe share an example of a collection, where both TextGrids and Pitchtiers are used? I can develop/extend a script that can be used for more general purposes. Maybe it is also a good idea to develop a new method for that?

The only thing I'm worried about is the number of lines in a collection Textgrid, especially for collections including audio files...

Best,
Pol

**Comment by bbTomas** [comment]
Thank you. I think the new method (e.g., collectionRead) is necessary because collections may contain many different objects. The return-variable type of the new method should also be considered. Probably a cell-array containing each object and its type?

Here are few example collections:
[collections.zip](https://github.com/bbTomas/mPraat/files/1369283/collections.zip)

**Comment by polvanrijn** [comment]
Cool, that very nice of you :-) I also found another assumption/possible bug in the current code: we're assuming all TextGrids are in the UTF-8 format, even the [default format is UTF-16](http://www.fon.hum.uva.nl/praat/manual/Unicode.html). I therefore changed a part of the code in `tgRead`. I changed

```
[fid, message] = fopen(fileName, 'r', 'n', 'UTF-8');
```

to:

```
% determine TextGrid encoding
encoding = DetectTextGridEncoding(fileName);

% the warning can be ignored, see https://de.mathworks.com/matlabcentral/answers/270857-how-to-read-16-bit-text-with-matlab
[fid, message] = fopen(fileName, 'r', 'n', encoding);
```

I used the handy function `DetectTextGridEncoding` by [Weirong Chen](https://de.mathworks.com/matlabcentral/fileexchange/50475-detect-textgrid-encoding).

This Saturday, I will take a look at the collection TextGrids :-) I also had an idea to make the code more generic: Make a core function that checks the TextGrids and Points within a certain Tier. This script can than be called for each Tier. Another nice aspect is that you can call this function from all kinds of functions like `tgRead`, `collectionRead`etc.. Do you get my idea? If yes, do you like it?

Best & thanks,
Pol

**Comment by bbTomas** [comment]
The encoding detection is a very good idea. Maybe I would split it to two parts:
* function textgrid = tgRead(fileName, encoding) 
  - with default value encoding = "UTF-8" to make it compatible with previous versions of mPraat
  - so user can set his own encoding and the performance is fast because there is no need to autodetect the encoding
* function tgDetectEncoding(fileName)
  - DetectTextGridEncoding
Do you think it is ok with the licence? We should ask Weirong Chen first, I hope he will agree

I am not sure if I get the idea of the generic function. Do you mean you call it on an unknowd type of object and it will tell: it is a textgrid, it is a pitchtier, it is a pitch...?

**Comment by polvanrijn** [comment]
Dear Tomas,

In my latest commit I created a function called `colRead`, which can read a Collection file. I didn't implement a `colWrite` yet, since I wasn't sure, whether your happy with my purposed implementation.
Next to that, I modified `tgRead`, `ptRead` and `pitchRead`. I added the automatic encoding detection, when no encoding is supplied. Next to that, I added a second output of each function that tells which line we are in the text file (`fid`). If we only ask for one output, e.g.: `tg = tgRead('demo/H.TextGrid')` only a TextGrid object will be returned, if we ask for `[tg, fid] = tgRead('demo/H.TextGrid')` also `fid` will be returned.
As for the automatic encoding detection, I wrote Weirong Chen and he very much agreed on using his function (I can send you the mail correspondence, if you want). :-)
I also wrote two other functions called `text = getTextInQuotes(str)` and `number = getNumberInLine(str, shortFormat)`. The first function will be given a string as parameter (usually a line, like 'Object class = "Pitch 1"') and the part in double quotes will be returned (in this case 'Pitch 1'). `getNumberInLine(str, shortFormat)` works similar: It gets a parameter with a statement, e.g. 'nCandidates = 3' and cuts of the number and converts it from a string to a number. The default value of  `shortFormat` is `false`; If it is `true` the given parameter will be returned as a number.

What do you think of it?

Best,
Pol

**Comment by bbTomas** [comment]
Hello Pol,
sorry for the delayed reply. Is the new commit public? I can only see the "revert" pull request.
The changes sound great and I am glad Weirong Chen agreed to include his code in the mPraat.
Thanks,
Tomas

**Comment by polvanrijn** [comment]
Sorry, something went wrong with commiting. Now it should work :-)

**Comment by bbTomas** [comment]
Well done! Thank you. I am going to make these additional changes and pull it into the new 1.0.9 version.

* contains(where, what) -> ~isempty(strfind(where, what))
  - to make it compatible with Matlab < 2016
* str2num -> str2double
  - it is faster (according to Matlab code-analyser hint)
* encoding: default (parameter missing) changed to 'UTF-8' (backward compatibility with previous mPraat versions), new option 'auto' calls tgDetectEncoding
  - Note: tgDetectEncoding reads the text file 3 times - it is slower, that is why I prefer to keep the default UTF-8 without tgDetectEncoding.
* removed "Unknown encoding" check: There are many 'unknown' encodings which are not officialy
supported by fopen() but they actually work. If the encoding is not supported by the current OS, fopen has its own error message.
* colRead: changed format of return variable
  - name of object was ignored
* colRead: added support for short-text format collections

**Comment by polvanrijn** [comment]
That's great! Thanks :-) Maybe we can brainstorm some day, how we can continue.

**Comment by bbTomas** [comment]
At the first step, I should implement these new functions into rPraat
package :-)

**Pull request merged**
